* to do
** features
*** query the db
**** datalog-style conditioning
Every variable in a valid query must appear in an "immediate condition query", a "such-that query", or in a sub-call to some other valid query. 
**** TODO kinds of queries
***** one-jump queries
****** 'Show me every collection involving oxygen.'
    Find oxygen's `Addr`, "ao".
    Run `positionsHeldBy index ao` to get a set of `(Role, Addr)`s.
    Return all those `Addr`s.
****** 'Show me every Rel using the "<> #needs <>" Tplt.'
    Find the address "at" of the template "<> needs <>".
    Run `positionsHeldBy index at` to get a set of `(Role, Addr)`s.
    Keep only the ones for which the `Role` is a `RoleTplt`.
    Return all the `Addr`s remaining.
****** 'Show me every Rel of the form "<> #needs oxygen".'
    Do the first two.
    Take their intersection.
***** TODO such-that queries
****** 'Show me every x for which  "x #needs oxygen".'
***** and, or
***** not
***** variety
**** a query type
*** represent rules in the db
*** Hash
*** edit a db
** minor
*** (awaiting response) Tests.curry:-- call `broken` fron the REPL?
  https://stackoverflow.com/questions/53547365/the-pakcs-repl-consider-something-undefined-but-the-module-defining-it-is-loade
*** Index.exprImgKey'default x = Just x -- TODO : Why the warning?
*** (awaiting response) add Util.sort to the List module
  https://mail.google.com/mail/u/0/#sent/KtbxLvHkVTXWJFRfxzwlKdBtLNPMLtGMcL
** change architecture
*** force full evaluation of index immediately
*** use ordinary hard-disk files rather than Rslt.Files
* some Curry functions I might need
** Hex-formatting a number
showInt 'x' Nothing (Just 1) (Just 1) 31
* pitfall & solved, I think
** ? conflicting definitions, (supposedly) in standard library
*** It happens if I import two libraries, unqualified, that define the same name
*** example
**** if I add this line to All.curry:
 import List as M
**** then I get these errors
 /home/jeff/logic/curry/install/pakcs-2.0.2/lib/.curry/List.icurry, line 6.1: Error:
     Multiple exports of name `delete' at:
       line 6.1
       line 4.1

 /home/jeff/logic/curry/install/pakcs-2.0.2/lib/.curry/List.icurry, line 49.1: Error:
     Multiple exports of name `sortBy' at:
       line 49.1
       line 17.1
